name: Collect Metrics
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests boto3
      - name: Collect and push metrics
        env:
          APP_URL: https://dashboard.catalinpatrut.com
          AWS_REGION: eu-central-1
          PROJECT_NAME: devops-dashboard
        run: |
          python scripts/collect_metrics.py